apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-api
  labels:
    app: clinic-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinic-api
  template:
    metadata:
      labels:
        app: clinic-api
    spec:
      containers:
        - name: clinic-api
          image: clinic-hexagonal:latest   # replace with your registry image (ACR, ECR, GHCR...)
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: clinic-config
            - secretRef:
                name: clinic-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 1Gi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
